name: PHP Linting

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  phplint:

    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v2
        - uses: michaelw90/PHP-Lint@master
